// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckFocused(arg1) {
  return window['go']['main']['App']['CheckFocused'](arg1);
}

export function GetRunningPrograms() {
  return window['go']['main']['App']['GetRunningPrograms']();
}

export function IncrementMoni(arg1, arg2) {
  return window['go']['main']['App']['IncrementMoni'](arg1, arg2);
}

export function LoadMoni() {
  return window['go']['main']['App']['LoadMoni']();
}

export function PauseDualTimer() {
  return window['go']['main']['App']['PauseDualTimer']();
}

export function Quit() {
  return window['go']['main']['App']['Quit']();
}

export function ResumeDualTimer() {
  return window['go']['main']['App']['ResumeDualTimer']();
}

export function SaveMoni(arg1) {
  return window['go']['main']['App']['SaveMoni'](arg1);
}

export function StartDualTimer(arg1, arg2) {
  return window['go']['main']['App']['StartDualTimer'](arg1, arg2);
}

export function StopDualTimer() {
  return window['go']['main']['App']['StopDualTimer']();
}
