// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckFocused(arg1) {
  return window['go']['main']['App']['CheckFocused'](arg1);
}

export function GetRunningPrograms() {
  return window['go']['main']['App']['GetRunningPrograms']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function PauseDualTimer() {
  return window['go']['main']['App']['PauseDualTimer']();
}

export function ResumeDualTimer() {
  return window['go']['main']['App']['ResumeDualTimer']();
}

export function StartDualTimer(arg1, arg2) {
  return window['go']['main']['App']['StartDualTimer'](arg1, arg2);
}

export function StopDualTimer() {
  return window['go']['main']['App']['StopDualTimer']();
}
